### ISSUE TITLE
Off-topic - favicon generator name

### ISSUE THREAD

**Issue by s1lviu** [aofdev/vue-firebase-auth-vuex#5]
Hello!

I saw that the app has many icons. I cannot find the tool for generating them.

Can you help me/us?

Thanks!

**Comment by aofdev** [comment]
i using this [Favicon Generator](https://realfavicongenerator.net/)

**Comment by s1lviu** [comment]
@aofdev it generates fewer than you have
<img src="https://i.imgur.com/HD9EQwn.png">

**Comment by aofdev** [comment]
try using [pwabuilder imageGenerator](https://www.pwabuilder.com/imageGenerator) @s1lviu
